// ===== FULL BIBLE DATA =====
// All 66 books with complete chapter/verse structure
// KJV Text for key verses, full navigation for all books

const BIBLE_BOOKS = {
  OT: [
    { id:'gen', name:'Genesis', abbr:'Gen', chapters:50 },
    { id:'exo', name:'Exodus', abbr:'Exo', chapters:40 },
    { id:'lev', name:'Leviticus', abbr:'Lev', chapters:27 },
    { id:'num', name:'Numbers', abbr:'Num', chapters:36 },
    { id:'deu', name:'Deuteronomy', abbr:'Deu', chapters:34 },
    { id:'jos', name:'Joshua', abbr:'Jos', chapters:24 },
    { id:'jdg', name:'Judges', abbr:'Jdg', chapters:21 },
    { id:'rut', name:'Ruth', abbr:'Rut', chapters:4 },
    { id:'1sa', name:'1 Samuel', abbr:'1Sa', chapters:31 },
    { id:'2sa', name:'2 Samuel', abbr:'2Sa', chapters:24 },
    { id:'1ki', name:'1 Kings', abbr:'1Ki', chapters:22 },
    { id:'2ki', name:'2 Kings', abbr:'2Ki', chapters:25 },
    { id:'1ch', name:'1 Chronicles', abbr:'1Ch', chapters:29 },
    { id:'2ch', name:'2 Chronicles', abbr:'2Ch', chapters:36 },
    { id:'ezr', name:'Ezra', abbr:'Ezr', chapters:10 },
    { id:'neh', name:'Nehemiah', abbr:'Neh', chapters:13 },
    { id:'est', name:'Esther', abbr:'Est', chapters:10 },
    { id:'job', name:'Job', abbr:'Job', chapters:42 },
    { id:'psa', name:'Psalms', abbr:'Psa', chapters:150 },
    { id:'pro', name:'Proverbs', abbr:'Pro', chapters:31 },
    { id:'ecc', name:'Ecclesiastes', abbr:'Ecc', chapters:12 },
    { id:'sng', name:'Song of Solomon', abbr:'Sng', chapters:8 },
    { id:'isa', name:'Isaiah', abbr:'Isa', chapters:66 },
    { id:'jer', name:'Jeremiah', abbr:'Jer', chapters:52 },
    { id:'lam', name:'Lamentations', abbr:'Lam', chapters:5 },
    { id:'eze', name:'Ezekiel', abbr:'Eze', chapters:48 },
    { id:'dan', name:'Daniel', abbr:'Dan', chapters:12 },
    { id:'hos', name:'Hosea', abbr:'Hos', chapters:14 },
    { id:'joe', name:'Joel', abbr:'Joe', chapters:3 },
    { id:'amo', name:'Amos', abbr:'Amo', chapters:9 },
    { id:'oba', name:'Obadiah', abbr:'Oba', chapters:1 },
    { id:'jon', name:'Jonah', abbr:'Jon', chapters:4 },
    { id:'mic', name:'Micah', abbr:'Mic', chapters:7 },
    { id:'nah', name:'Nahum', abbr:'Nah', chapters:3 },
    { id:'hab', name:'Habakkuk', abbr:'Hab', chapters:3 },
    { id:'zep', name:'Zephaniah', abbr:'Zep', chapters:3 },
    { id:'hag', name:'Haggai', abbr:'Hag', chapters:2 },
    { id:'zec', name:'Zechariah', abbr:'Zec', chapters:14 },
    { id:'mal', name:'Malachi', abbr:'Mal', chapters:4 },
  ],
  NT: [
    { id:'mat', name:'Matthew', abbr:'Mat', chapters:28 },
    { id:'mar', name:'Mark', abbr:'Mar', chapters:16 },
    { id:'luk', name:'Luke', abbr:'Luk', chapters:24 },
    { id:'joh', name:'John', abbr:'Joh', chapters:21 },
    { id:'act', name:'Acts', abbr:'Act', chapters:28 },
    { id:'rom', name:'Romans', abbr:'Rom', chapters:16 },
    { id:'1co', name:'1 Corinthians', abbr:'1Co', chapters:16 },
    { id:'2co', name:'2 Corinthians', abbr:'2Co', chapters:13 },
    { id:'gal', name:'Galatians', abbr:'Gal', chapters:6 },
    { id:'eph', name:'Ephesians', abbr:'Eph', chapters:6 },
    { id:'php', name:'Philippians', abbr:'Php', chapters:4 },
    { id:'col', name:'Colossians', abbr:'Col', chapters:4 },
    { id:'1th', name:'1 Thessalonians', abbr:'1Th', chapters:5 },
    { id:'2th', name:'2 Thessalonians', abbr:'2Th', chapters:3 },
    { id:'1ti', name:'1 Timothy', abbr:'1Ti', chapters:6 },
    { id:'2ti', name:'2 Timothy', abbr:'2Ti', chapters:4 },
    { id:'tit', name:'Titus', abbr:'Tit', chapters:3 },
    { id:'phm', name:'Philemon', abbr:'Phm', chapters:1 },
    { id:'heb', name:'Hebrews', abbr:'Heb', chapters:13 },
    { id:'jam', name:'James', abbr:'Jam', chapters:5 },
    { id:'1pe', name:'1 Peter', abbr:'1Pe', chapters:5 },
    { id:'2pe', name:'2 Peter', abbr:'2Pe', chapters:3 },
    { id:'1jo', name:'1 John', abbr:'1Jo', chapters:5 },
    { id:'2jo', name:'2 John', abbr:'2Jo', chapters:1 },
    { id:'3jo', name:'3 John', abbr:'3Jo', chapters:1 },
    { id:'jud', name:'Jude', abbr:'Jud', chapters:1 },
    { id:'rev', name:'Revelation', abbr:'Rev', chapters:22 },
  ]
};

// Full KJV text for popular chapters
const BIBLE_TEXT = {
  'gen-1': {
    title: 'Genesis 1', subtitle: 'The Creation',
    verses: [
      "In the beginning God created the heaven and the earth.",
      "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.",
      "And God said, Let there be light: and there was light.",
      "And God saw the light, that it was good: and God divided the light from the darkness.",
      "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.",
      "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.",
      "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.",
      "And God called the firmament Heaven. And the evening and the morning were the second day.",
      "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.",
      "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.",
      "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.",
      "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.",
      "And the evening and the morning were the third day.",
      "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:",
      "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.",
      "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.",
      "And God set them in the firmament of the heaven to give light upon the earth,",
      "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.",
      "And the evening and the morning were the fourth day.",
      "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.",
      "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good.",
      "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.",
      "And the evening and the morning were the fifth day.",
      "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so.",
      "And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good.",
      "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.",
      "So God created man in his own image, in the image of God created he him; male and female created he them.",
      "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth.",
      "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat.",
      "And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so.",
      "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day."
    ]
  },
  'psa-23': {
    title: 'Psalm 23', subtitle: 'The Lord is My Shepherd',
    verses: [
      "The LORD is my shepherd; I shall not want.",
      "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
      "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
      "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
      "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
      "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever."
    ]
  },
  'psa-91': {
    title: 'Psalm 91', subtitle: 'He That Dwelleth in the Secret Place',
    verses: [
      "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.",
      "I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.",
      "Surely he shall deliver thee from the snare of the fowler, and from the noisome pestilence.",
      "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler.",
      "Thou shalt not be afraid for the terror by night; nor for the arrow that flieth by day;",
      "Nor for the pestilence that walketh in darkness; nor for the destruction that wasteth at noonday.",
      "A thousand shall fall at thy side, and ten thousand at thy right hand; but it shall not come nigh thee.",
      "Only with thine eyes shalt thou behold and see the reward of the wicked.",
      "Because thou hast made the LORD, which is my refuge, even the most High, thy habitation;",
      "There shall no evil befall thee, neither shall any plague come nigh thy dwelling.",
      "For he shall give his angels charge over thee, to keep thee in all thy ways.",
      "They shall bear thee up in their hands, lest thou dash thy foot against a stone.",
      "Thou shalt tread upon the lion and adder: the young lion and the dragon shalt thou trample under feet.",
      "Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name.",
      "He shall call upon me, and I will answer him: I will be with him in trouble; I will deliver him, and honour him.",
      "With long life will I satisfy him, and shew him my salvation."
    ]
  },
  'joh-3': {
    title: 'John 3', subtitle: 'Jesus and Nicodemus',
    verses: [
      "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
      "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
      "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
      "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
      "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
      "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit.",
      "Marvel not that I said unto thee, Ye must be born again.",
      "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
      "Nicodemus answered and said unto him, How can these things be?",
      "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?",
      "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
      "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
      "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
      "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:",
      "That whosoever believeth in him should not perish, but have eternal life.",
      "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
      "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
      "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
      "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil.",
      "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved.",
      "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God."
    ]
  },
  'rom-8': {
    title: 'Romans 8', subtitle: 'Life in the Spirit',
    verses: [
      "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
      "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
      "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh:",
      "That the righteousness of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
      "For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit.",
      "For to be carnally minded is death; but to be spiritually minded is life and peace.",
      "Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be.",
      "So then they that are in the flesh cannot please God.",
      "But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you. Now if any man have not the Spirit of Christ, he is none of his.",
      "And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.",
      "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you.",
      "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh.",
      "For if ye live after the flesh, ye shall die: but if ye through the Spirit do mortify the deeds of the body, ye shall live.",
      "For as many as are led by the Spirit of God, they are the sons of God.",
      "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father.",
      "The Spirit itself beareth witness with our spirit, that we are the children of God:",
      "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.",
      "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
      "For the earnest expectation of the creature waiteth for the manifestation of the sons of God.",
      "For the creature was made subject to vanity, not willingly, but by reason of him who hath subjected the same in hope,",
      "Because the creature itself also shall be delivered from the bondage of corruption into the glorious liberty of the children of God.",
      "For we know that the whole creation groaneth and travaileth in pain together until now.",
      "And not only they, but ourselves also, which have the firstfruits of the Spirit, even we ourselves groan within ourselves, waiting for the adoption, to wit, the redemption of our body.",
      "For we are saved by hope: but hope that is seen is not hope: for what a man seeth, why doth he yet hope for?",
      "But if we hope for that we see not, then do we with patience wait for it.",
      "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
      "And he that searcheth the hearts knoweth what is the mind of the Spirit, because he maketh intercession for the saints according to the will of God.",
      "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
      "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, that he might be the firstborn among many brethren.",
      "Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified.",
      "What shall we then say to these things? If God be for us, who can be against us?",
      "He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?",
      "Who shall lay any thing to the charge of God's elect? It is God that justifieth.",
      "Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us.",
      "Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?",
      "As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.",
      "Nay, in all these things we are more than conquerors through him that loved us.",
      "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,",
      "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
    ]
  },
  'php-4': {
    title: 'Philippians 4', subtitle: 'Rejoice in the Lord',
    verses: [
      "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord, my dearly beloved.",
      "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord.",
      "And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life.",
      "Rejoice in the Lord always: and again I say, Rejoice.",
      "Let your moderation be known unto all men. The Lord is at hand.",
      "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
      "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
      "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.",
      "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you.",
      "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again; wherein ye were also careful, but ye lacked opportunity.",
      "Not that I desire a gift: but I desire fruit that may abound to your account.",
      "But I have all, and abound: I am full, having received of Epaphroditus the things which were sent from you, an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God.",
      "But my God shall supply all your need according to his riches in glory by Christ Jesus.",
      "Now unto God and our Father be glory for ever and ever. Amen.",
      "Salute every saint in Christ Jesus. The brethren which are with me greet you.",
      "All the saints salute you, chiefly they that are of Caesar's household.",
      "The grace of our Lord Jesus Christ be with you all. Amen.",
      "I can do all things through Christ which strengtheneth me.",
      "Notwithstanding ye have well done, that ye did communicate with my affliction.",
      "Now ye Philippians know also, that in the beginning of the gospel, when I departed from Macedonia, no church communicated with me as concerning giving and receiving, but ye only.",
      "For even in Thessalonica ye sent once and again unto my necessity.",
      "Not because I desire a gift: but I desire fruit that may abound to your account."
    ]
  },
  'isa-40': {
    title: 'Isaiah 40', subtitle: 'Comfort for God\'s People',
    verses: [
      "Comfort ye, comfort ye my people, saith your God.",
      "Speak ye comfortably to Jerusalem, and cry unto her, that her warfare is accomplished, that her iniquity is pardoned: for she hath received of the LORD's hand double for all her sins.",
      "The voice of him that crieth in the wilderness, Prepare ye the way of the LORD, make straight in the desert a highway for our God.",
      "Every valley shall be exalted, and every mountain and hill shall be made low: and the crooked shall be made straight, and the rough places plain:",
      "And the glory of the LORD shall be revealed, and all flesh shall see it together: for the mouth of the LORD hath spoken it.",
      "The voice said, Cry. And he said, What shall I cry? All flesh is grass, and all the goodliness thereof is as the flower of the field:",
      "The grass withereth, the flower fadeth: because the spirit of the LORD bloweth upon it: surely the people is grass.",
      "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.",
      "O Zion, that bringest good tidings, get thee up into the high mountain; O Jerusalem, that bringest good tidings, lift up thy voice with strength; lift it up, be not afraid; say unto the cities of Judah, Behold your God!",
      "Behold, the Lord GOD will come with strong hand, and his arm shall rule for him: behold, his reward is with him, and his work before him.",
      "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young.",
      "Who hath measured the waters in the hollow of his hand, and meted out heaven with the span, and comprehended the dust of the earth in a measure, and weighed the mountains in scales, and the hills in a balance?",
      "Who hath directed the Spirit of the LORD, or being his counsellor hath taught him?",
      "With whom took he counsel, and who instructed him, and taught him in the path of judgment, and taught him knowledge, and shewed to him the way of understanding?",
      "Behold, the nations are as a drop of a bucket, and are counted as the small dust of the balance: behold, he taketh up the isles as a very little thing.",
      "And Lebanon is not sufficient to burn, nor the beasts thereof sufficient for a burnt offering.",
      "All nations before him are as nothing; and they are counted to him less than nothing, and vanity.",
      "To whom then will ye liken God? or what likeness will ye compare unto him?",
      "The workman melteth a graven image, and the goldsmith spreadeth it over with gold, and casteth silver chains.",
      "He that is so impoverished that he hath no oblation chooseth a tree that will not rot; he seeketh unto him a cunning workman to prepare a graven image, that shall not be moved.",
      "Have ye not known? have ye not heard? hath it not been told you from the beginning? have ye not understood from the foundations of the earth?",
      "It is he that sitteth upon the circle of the earth, and the inhabitants thereof are as grasshoppers; that stretcheth out the heavens as a curtain, and spreadeth them out as a tent to dwell in:",
      "That bringeth the princes to nothing; he maketh the judges of the earth as vanity.",
      "Yea, they shall not be planted; yea, they shall not be sown: yea, their stock shall not take root in the earth: and he shall also blow upon them, and they shall wither, and the whirlwind shall take them away as stubble.",
      "To whom then will ye liken me, or shall I be equal? saith the Holy One.",
      "Lift up your eyes on high, and behold who hath created these things, that bringeth out their host by number: he calleth them all by names by the greatness of his might, for that he is strong in power; not one faileth.",
      "Why sayest thou, O Jacob, and speakest, O Israel, My way is hid from the LORD, and my judgment is passed over from my God?",
      "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding.",
      "He giveth power to the faint; and to them that have no might he increaseth strength.",
      "Even the youths shall faint and be weary, and the young men shall utterly fall:",
      "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."
    ]
  },
  'mat-5': {
    title: 'Matthew 5', subtitle: 'The Sermon on the Mount',
    verses: [
      "And seeing the multitudes, he went up into a mountain: and when he was set, his disciples came unto him:",
      "And he opened his mouth, and taught them, saying,",
      "Blessed are the poor in spirit: for theirs is the kingdom of heaven.",
      "Blessed are they that mourn: for they shall be comforted.",
      "Blessed are the meek: for they shall inherit the earth.",
      "Blessed are they which do hunger and thirst after righteousness: for they shall be filled.",
      "Blessed are the merciful: for they shall obtain mercy.",
      "Blessed are the pure in heart: for they shall see God.",
      "Blessed are the peacemakers: for they shall be called the children of God.",
      "Blessed are they which are persecuted for righteousness' sake: for theirs is the kingdom of heaven.",
      "Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake.",
      "Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you.",
      "Ye are the salt of the earth: but if the salt have lost his savour, wherewith shall it be salted? it is thenceforth good for nothing, but to be cast out, and to be trodden under foot of men.",
      "Ye are the light of the world. A city that is set on an hill cannot be hid.",
      "Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house.",
      "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
      "Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil.",
      "For verily I say unto you, Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law, till all be fulfilled.",
      "Whosoever therefore shall break one of these least commandments, and shall teach men so, he shall be called the least in the kingdom of heaven: but whosoever shall do and teach them, the same shall be called great in the kingdom of heaven.",
      "For I say unto you, That except your righteousness shall exceed the righteousness of the scribes and Pharisees, ye shall in no case enter into the kingdom of heaven.",
      "Ye have heard that it was said of them of old time, Thou shalt not kill; and whosoever shall kill shall be in danger of the judgment:",
      "But I say unto you, That whosoever is angry with his brother without a cause shall be in danger of the judgment: and whosoever shall say to his brother, Raca, shall be in danger of the council: but whosoever shall say, Thou fool, shall be in danger of hell fire.",
      "Therefore if thou bring thy gift to the altar, and there rememberest that thy brother hath ought against thee;",
      "Leave there thy gift before the altar, and go thy way; first be reconciled to thy brother, and then come and offer thy gift.",
      "Agree with thine adversary quickly, whiles thou art in the way with him; lest at any time the adversary deliver thee to the judge, and the judge deliver thee to the officer, and thou be cast into prison.",
      "Verily I say unto thee, Thou shalt by no means come out thence, till thou hast paid the uttermost farthing.",
      "Ye have heard that it was said by them of old time, Thou shalt not commit adultery:",
      "But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart.",
      "And if thy right eye offend thee, pluck it out, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell.",
      "And if thy right hand offend thee, cut it off, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell.",
      "It hath been said, Whosoever shall put away his wife, let him give her a writing of divorcement:",
      "But I say unto you, That whosoever shall put away his wife, saving for the cause of fornication, causeth her to commit adultery: and whosoever shall marry her that is divorced committeth adultery.",
      "Again, ye have heard that it hath been said by them of old time, Thou shalt not forswear thyself, but shalt perform unto the Lord thine oaths:",
      "But I say unto you, Swear not at all; neither by heaven; for it is God's throne:",
      "Nor by the earth; for it is his footstool: neither by Jerusalem; for it is the city of the great King.",
      "Neither shalt thou swear by thy head, because thou canst not make one hair white or black.",
      "But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil.",
      "Ye have heard that it hath been said, An eye for an eye, and a tooth for a tooth:",
      "But I say unto you, That ye resist not evil: but whosoever shall smite thee on thy right cheek, turn to him the other also.",
      "And if any man will sue thee at the law, and take away thy coat, let him have thy cloke also.",
      "And whosoever shall compel thee to go a mile, go with him twain.",
      "Give to him that asketh thee, and from him that would borrow of thee turn not thou away.",
      "Ye have heard that it hath been said, Thou shalt love thy neighbour, and hate thine enemy.",
      "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;",
      "That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust.",
      "For if ye love them which love you, what reward have ye? do not even the publicans the same?",
      "And if ye salute your brethren only, what do ye more than others? do not even the publicans so?",
      "Be ye therefore perfect, even as your Father which is in heaven is perfect."
    ]
  },
  'pro-3': {
    title: 'Proverbs 3', subtitle: 'Trust in the Lord',
    verses: [
      "My son, forget not my law; but let thine heart keep my commandments:",
      "For length of days, and long life, and peace, shall they add to thee.",
      "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:",
      "So shalt thou find favour and good understanding in the sight of God and man.",
      "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
      "In all thy ways acknowledge him, and he shall direct thy paths.",
      "Be not wise in thine own eyes: fear the LORD, and depart from evil.",
      "It shall be health to thy navel, and marrow to thy bones.",
      "Honour the LORD with thy substance, and with the firstfruits of all thine increase:",
      "So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.",
      "My son, despise not the chastening of the LORD; neither be weary of his correction:",
      "For whom the LORD loveth he correcteth; even as a father the son in whom he delighteth.",
      "Happy is the man that findeth wisdom, and the man that getteth understanding.",
      "For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold.",
      "She is more precious than rubies: and all the things thou canst desire are not to be compared unto her.",
      "Length of days is in her right hand; and in her left hand riches and honour.",
      "Her ways are ways of pleasantness, and all her paths are peace.",
      "She is a tree of life to them that lay hold upon her: and happy is every one that retaineth her.",
      "The LORD by wisdom hath founded the earth; by understanding hath he established the heavens.",
      "By his knowledge the depths are broken up, and the clouds drop down the dew.",
      "My son, let not them depart from thine eyes: keep sound wisdom and discretion:",
      "So shall they be life unto thy soul, and grace to thy neck.",
      "Then shalt thou walk in thy way safely, and thy foot shall not stumble.",
      "When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet.",
      "Be not afraid of sudden fear, neither of the desolation of the wicked, when it cometh.",
      "For the LORD shall be thy confidence, and shall keep thy foot from being taken.",
      "Withhold not good from them to whom it is due, when it is in the power of thine hand to do it.",
      "Say not unto thy neighbour, Go, and come again, and to morrow I will give; when thou hast it by thee.",
      "Devise not evil against thy neighbour, seeing he dwelleth securely by thee.",
      "Strive not with a man without cause, if he have done thee no harm.",
      "Envy thou not the oppressor, and choose none of his ways.",
      "For the froward is abomination to the LORD: but his secret is with the righteous.",
      "The curse of the LORD is in the house of the wicked: but he blesseth the habitation of the just.",
      "Surely he scorneth the scorners: but he giveth grace unto the lowly.",
      "The wise shall inherit glory: but shame shall be the promotion of fools."
    ]
  },
  'heb-11': {
    title: 'Hebrews 11', subtitle: 'Faith\'s Hall of Fame',
    verses: [
      "Now faith is the substance of things hoped for, the evidence of things not seen.",
      "For by it the elders obtained a good report.",
      "Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.",
      "By faith Abel offered unto God a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, God testifying of his gifts: and by it he being dead yet speaketh.",
      "By faith Enoch was translated that he should not see death; and was not found, because God had translated him: for before his translation he had this testimony, that he pleased God.",
      "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
      "By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith.",
      "By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went.",
      "By faith he sojourned in the land of promise, as in a strange country, dwelling in tabernacles with Isaac and Jacob, the heirs with him of the same promise:",
      "For he looked for a city which hath foundations, whose builder and maker is God.",
      "Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised.",
      "Therefore sprang there even of one, and him as good as dead, so many as the stars of the sky in multitude, and as the sand which is by the sea shore innumerable.",
      "These all died in faith, not having received the promises, but having seen them afar off, and were persuaded of them, and embraced them, and confessed that they were strangers and pilgrims on the earth.",
      "For they that say such things declare plainly that they seek a country.",
      "And truly, if they had been mindful of that country from whence they came out, they might have had opportunity to have returned.",
      "But now they desire a better country, that is, an heavenly: wherefore God is not ashamed to be called their God: for he hath prepared for them a city.",
      "By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten son,",
      "Of whom it was said, That in Isaac shall thy seed be called:",
      "Accounting that God was able to raise him up, even from the dead; from whence also he received him in a figure.",
      "By faith Isaac blessed Jacob and Esau concerning things to come.",
      "By faith Jacob, when he was a dying, blessed both the sons of Joseph; and worshipped, leaning upon the top of his staff.",
      "By faith Joseph, when he died, made mention of the departing of the children of Israel; and gave commandment concerning his bones.",
      "By faith Moses, when he was born, was hid three months of his parents, because they saw he was a proper child; and they were not afraid of the king's commandment.",
      "By faith Moses, when he was come to years, refused to be called the son of Pharaoh's daughter;",
      "Choosing rather to suffer affliction with the people of God, than to enjoy the pleasures of sin for a season;",
      "Esteeming the reproach of Christ greater riches than the treasures in Egypt: for he had respect unto the recompence of the reward.",
      "By faith he forsook Egypt, not fearing the wrath of the king: for he endured, as seeing him who is invisible.",
      "Through faith he kept the passover, and the sprinkling of blood, lest he that destroyed the firstborn should touch them.",
      "By faith they passed through the Red sea as by dry land: which the Egyptians assaying to do were drowned.",
      "By faith the walls of Jericho fell down, after they were compassed about seven days.",
      "By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace.",
      "And what shall I more say? for the time would fail me to tell of Gedeon, and of Barak, and of Samson, and of Jephthae; of David also, and Samuel, and of the prophets:",
      "Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions,",
      "Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong, waxed valiant in fight, turned to flight the armies of the aliens.",
      "Women received their dead raised to life again: and others were tortured, not accepting deliverance; that they might obtain a better resurrection:",
      "And others had trial of cruel mockings and scourgings, yea, moreover of bonds and imprisonment:",
      "They were stoned, they were sawn asunder, were tempted, were slain with the sword: they wandered about in sheepskins and goatskins; being destitute, afflicted, tormented;",
      "Of whom the world was not worthy: they wandered in deserts, and in mountains, and in dens and caves of the earth.",
      "And these all, having obtained a good report through faith, received not the promise:",
      "God having provided some better thing for us, that they without us should not be made perfect."
    ]
  },
  'rev-1': {
    title: 'Revelation 1', subtitle: 'The Vision of Christ',
    verses: [
      "The Revelation of Jesus Christ, which God gave unto him, to shew unto his servants things which must shortly come to pass; and he sent and signified it by his angel unto his servant John:",
      "Who bare record of the word of God, and of the testimony of Jesus Christ, and of all things that he saw.",
      "Blessed is he that readeth, and they that hear the words of this prophecy, and keep those things which are written therein: for the time is at hand.",
      "John to the seven churches which are in Asia: Grace be unto you, and peace, from him which is, and which was, and which is to come; and from the seven Spirits which are before his throne;",
      "And from Jesus Christ, who is the faithful witness, and the first begotten of the dead, and the prince of the kings of the earth. Unto him that loved us, and washed us from our sins in his own blood,",
      "And hath made us kings and priests unto God and his Father; to him be glory and dominion for ever and ever. Amen.",
      "Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen.",
      "I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.",
      "I John, who also am your brother, and companion in tribulation, and in the kingdom and patience of Jesus Christ, was in the isle that is called Patmos, for the word of God, and for the testimony of Jesus Christ.",
      "I was in the Spirit on the Lord's day, and heard behind me a great voice, as of a trumpet,",
      "Saying, I am Alpha and Omega, the first and the last: and, What thou seest, write in a book, and send it unto the seven churches which are in Asia; unto Ephesus, and unto Smyrna, and unto Pergamos, and unto Thyatira, and unto Sardis, and unto Philadelphia, and unto Laodicea.",
      "And I turned to see the voice that spake with me. And being turned, I saw seven golden candlesticks;",
      "And in the midst of the seven candlesticks one like unto the Son of man, clothed with a garment down to the foot, and girt about the paps with a golden girdle.",
      "His head and his hairs were white like wool, as white as snow; and his eyes were as a flame of fire;",
      "And his feet like unto fine brass, as if they burned in a furnace; and his voice as the sound of many waters.",
      "And he had in his right hand seven stars: and out of his mouth went a sharp twoedged sword: and his countenance was as the sun shineth in his strength.",
      "And when I saw him, I fell at his feet as dead. And he laid his right hand upon me, saying unto me, Fear not; I am the first and the last:",
      "I am he that liveth, and was dead; and, behold, I am alive for evermore, Amen; and have the keys of hell and of death.",
      "Write the things which thou hast seen, and the things which are, and the things which shall be hereafter;",
      "The mystery of the seven stars which thou sawest in my right hand, and the seven golden candlesticks. The seven stars are the angels of the seven churches: and the seven candlesticks which thou sawest are the seven churches."
    ]
  }
};

// Featured chapters for quick navigation
const FEATURED_CHAPTERS = [
  { key:'gen-1', label:'Genesis 1', desc:'The Creation' },
  { key:'psa-23', label:'Psalm 23', desc:'The Lord is My Shepherd' },
  { key:'psa-91', label:'Psalm 91', desc:'Under His Wings' },
  { key:'pro-3', label:'Proverbs 3', desc:'Trust in the Lord' },
  { key:'isa-40', label:'Isaiah 40', desc:'They shall mount up with wings' },
  { key:'mat-5', label:'Matthew 5', desc:'The Beatitudes' },
  { key:'joh-3', label:'John 3', desc:'Born Again & John 3:16' },
  { key:'rom-8', label:'Romans 8', desc:'No condemnation in Christ' },
  { key:'php-4', label:'Philippians 4', desc:'I can do all things' },
  { key:'heb-11', label:'Hebrews 11', desc:'Faith\'s Hall of Fame' },
  { key:'rev-1', label:'Revelation 1', desc:'The Vision of Christ' },
];
